var insights = [
  {
    id: 1,
    value: "Marketing",
    icon: "basket-fill",
    category_id: 1,
    color: "#8A2BE2",
  },
  {
    id: 2,
    value: "Business Development",
    icon: "calendar2-event-fill",
    category_id: 1,
    color: "#307D7E",
  },
  {
    id: 3,
    value: "Accounting",
    icon: "suit-club-fill",
    category_id: 1,
    color: "#001414",
  },

  {
    id: 1,
    value: "Networking",
    icon: "signpost2",
    category_id: 2,
    color: "#7E354D",
  },
  {
    id: 2,
    value: "Upskilling",
    icon: "slack",
    category_id: 2,
    color: "#C32148",
  },
  {
    id: 3,
    value: "Negotiation",
    icon: "archive",
    category_id: 2,
    color: "#483D8B",
  },
  {
    id: 4,
    value: "Leadership",
    icon: "stop-btn-fill",
    category_id: 2,
    color: "#504A4B",
  },

  {
    id: 1,
    value: "Start Up",
    icon: "server",
    category_id: 3,
    color: "#0020C2",
  },
  {
    id: 2,
    value: "Programming",
    icon: "cpu",
    category_id: 3,
    color: "#347C2C",
  },
  {
    id: 3,
    value: "Design",
    icon: "collection-fill",
    category_id: 3,
    color: "#191970",
  },
  {
    id: 4,
    value: "Blockchain",
    icon: "globe",
    category_id: 3,
    color: "#728C00",
  },
  {
    id: 5,
    value: "Space",
    icon: "card-heading",
    category_id: 3,
    color: "#3C565B",
  },
  {
    id: 1,
    value: "Money",
    icon: "tags",
    category_id: 4,
    color: "#A91FFF",
  },

  {
    id: 2,
    value: "Stock",
    icon: "diagram2-fill",
    category_id: 4,
    color: "#3C565B",
  },
  {
    id: 3,
    value: "Real Estate",
    icon: "diagram2-fill",
    category_id: 4,
    color: "#3C565B",
  },
  {
    id: 4,
    value: "Crypto",
    icon: "diagram2-fill",
    category_id: 4,
    color: "#3C565B",
  },
  {
    id: 5,
    value: "Investment",
    icon: "diagram2-fill",
    category_id: 4,
    color: "#3C565B",
  },

  {
    id: 1,
    value: "Physical Fitness",
    icon: "diagram2-fill",
    category_id: 5,
    color: "#3C565B",
  },
  {
    id: 2,
    value: "Mental Health",
    icon: "diagram2-fill",
    category_id: 5,
    color: "#3C565B",
  },
  {
    id: 3,
    value: "Nutrition",
    icon: "diagram2-fill",
    category_id: 5,
    color: "#3C565B",
  },
  {
    id: 4,
    value: "Lifestyle",
    icon: "diagram2-fill",
    category_id: 5,
    color: "#3C565B",
  },

  {
    id: 1,
    value: "Betting",
    icon: "joystick",
    category_id: 6,
    color: "#78866B",
  },
  {
    id: 2,
    value: "Sports",
    icon: "globe",
    category_id: 6,
    color: "#728C00",
  },
  {
    id: 3,
    value: "Gaming",
    icon: "controller",
    category_id: 6,
    color: "#667C26",
  },
  {
    id: 4,
    value: "Pop Culture",
    icon: "speaker-fill",
    category_id: 6,
    color: "#7ecc00",
  },
  {
    id: 5,
    value: "Music",
    icon: "rss",
    category_id: 6,
    color: "#66AF97",
  },

  {
    id: 1,
    value: "Religion",
    icon: "journal-bookmark-fill",
    category_id: 7,
    color: "#4863A0",
  },
  {
    id: 2,
    value: "Religion",
    icon: "shield-plus",
    category_id: 7,
    color: "#2B3856",
  },
  {
    id: 3,
    value: "Politics",
    icon: "stop-btn-fill",
    category_id: 7,
    color: "#504A4B",
  },
  {
    id: 4,
    value: "Environment",
    icon: "life-preserver",
    category_id: 7,
    color: "#6D7B8D",
  },
];

export default insights;
