var insights = [
  " Global News",
  "SDGs",
  "Marketing",
  "Business Management",
  "Entrepreneurship",
  "Productivity",
  "Mental health",
  "Personal Development",
  "Football",
  "Sports",
  "Gaming",
  "Tech",
  "Creativity",
  "Art",
  "Pop Culture",
  "Politics",
  "Global Trends",
  "Feminism",
  "Racism",
  "Fitness",
  "Wellness",
  "Religion",
  "Spirituality",
  "Start Up",
  "Love",
  "Relationships",
  "Parenting",
  "Psychology",
  "The Future",
  "Literature",
  "Literacy",
  "Writing",
  "Social Impact",
  "Money Adviser",
  "Fund Management ",
  "Crypto",
  "Legal",
  "Law",
  "Public Speaking",
  "New Media",
  "Show Biz",
  "Networking ",
  "Fintech",
  "Leisure",
  "Fashion ",
  "Music",
  "Digital Media",
  "Healing",
  "Agriculture",
  "Agrotech ",
  "Finance",
  "Motherhood",
  "Culinary",
  "Living",
  "Interiors ",
  "Spaces",
  "Corporate",
  "Languages",
  "Career",
  "Meditation",
];

export default insights;
